apiVersion: xlr.digital.ai/v1alpha1
kind: DigitalaiRelease
metadata:
  name: dai-xlr
spec:
  AdminPassword: 'customerAdminPassword'
  HealthPeriodScans: 10
  HealthProbeFailureThreshold: 12
  HealthProbes: true
  HealthProbesLivenessTimeout: 60
  HealthProbesReadinessTimeout: 60
  ImagePullPolicy: Always
  ImageRepository: xebialabs/xl-release
  ImageTag: "23.1.0"
  ## xebialabs/tiny-tools image version

  ## Ref: https://hub.docker.com/r/xebialabs/tiny-tools/tags
  TinyToolsImageRepository: "xebialabs/tiny-tools"
  TinyToolsImageTag: "22.2.0"
